"""Small declarative objects used by the public :func:`kurversc.fit` API."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

import pandas as pd


Key = str | tuple[str, ...]
Source = str | Path | pd.DataFrame


def _as_key(value: str | Sequence[str] | None, *, field: str) -> Key | None:
    if value is None:
        return None
    if isinstance(value, str):
        if not value:
            raise ValueError(f"{field} must not be empty")
        return value
    parts = tuple(value)
    if not parts or any(not isinstance(part, str) or not part for part in parts):
        raise ValueError(f"{field} must contain non-empty column names")
    return parts[0] if len(parts) == 1 else parts


@dataclass(frozen=True)
class Table:
    """A relational feature table.

    ``source`` may be a DataFrame, CSV/Parquet path, or a table/view name on
    the supplied DuckDB connection.
    """

    source: Source
    key: Key | None = None
    name: str | None = None
    date: str | None = None
    timeless: bool = False
    prefix: str | None = None
    columns: tuple[str, ...] | None = None
    context_keys: tuple[str, ...] = ()
    search_source: Source | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "key", _as_key(self.key, field="Table.key"))
        if self.date is not None and self.timeless:
            raise ValueError(
                "Table.date and Table.timeless=True are mutually exclusive"
            )
        if self.columns is not None:
            object.__setattr__(self, "columns", tuple(self.columns))
        object.__setattr__(
            self, "context_keys", tuple(dict.fromkeys(self.context_keys))
        )


@dataclass(frozen=True)
class Labels:
    """Labels and their train/validation/test split metadata."""

    source: Source
    target: str | None = None
    key: Key | None = None
    timestamp: str | None = None
    split: str | None = None
    train_value: Any = "train"
    validation_value: Any = "validation"
    test_value: Any = "test"
    search_source: Source | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "key", _as_key(self.key, field="Labels.key"))


@dataclass(frozen=True)
class GraphLabels:
    """Labels generated by GraphReduce from a related event table.

    Each cutoff produces historical features and a future-window target using
    the label node's native ``prep_for_labels`` and ``default_label`` path.
    """

    table: str
    field: str
    operation: str = "bool"
    period_days: int = 30
    train_cutoffs: tuple[Any, ...] = ()
    validation_cutoffs: tuple[Any, ...] = ()
    test_cutoffs: tuple[Any, ...] = ()
    target: str = "label"

    def __post_init__(self) -> None:
        if not self.table or not self.field or not self.target:
            raise ValueError("GraphLabels table, field, and target must not be empty")
        if self.period_days < 1:
            raise ValueError("GraphLabels.period_days must be positive")
        train = tuple(pd.Timestamp(value) for value in self.train_cutoffs)
        validation = tuple(pd.Timestamp(value) for value in self.validation_cutoffs)
        test = tuple(pd.Timestamp(value) for value in self.test_cutoffs)
        if not train or not validation:
            raise ValueError(
                "GraphLabels requires at least one train and validation cutoff"
            )
        object.__setattr__(self, "train_cutoffs", train)
        object.__setattr__(self, "validation_cutoffs", validation)
        object.__setattr__(self, "test_cutoffs", test)


@dataclass(frozen=True)
class Relationship:
    """A directed GraphReduce edge from parent grain to a related table."""

    parent: str
    child: str
    parent_key: Key
    child_key: Key
    reduce: bool = True

    def __post_init__(self) -> None:
        object.__setattr__(
            self, "parent_key", _as_key(self.parent_key, field="parent_key")
        )
        object.__setattr__(
            self, "child_key", _as_key(self.child_key, field="child_key")
        )


def coerce_table(
    value: Table | Source,
    *,
    key: Key | Sequence[str] | None = None,
    name: str | None = None,
    date: str | None = None,
    timeless: bool = False,
) -> Table:
    if isinstance(value, Table):
        return value
    return Table(
        value,
        key=_as_key(key, field="parent_key"),
        name=name,
        date=date,
        timeless=timeless,
    )


def coerce_labels(
    value: Labels | Source,
    *,
    target: str | None,
    key: Key | Sequence[str] | None,
    timestamp: str | None,
    split: str | None,
) -> Labels:
    if isinstance(value, Labels):
        return value
    return Labels(
        value,
        target=target,
        key=_as_key(key, field="label_key"),
        timestamp=timestamp,
        split=split,
    )


def coerce_relationship(value: Relationship | Mapping[str, Any]) -> Relationship:
    if isinstance(value, Relationship):
        return value
    aliases = dict(value)
    if "relation" in aliases and "child" not in aliases:
        aliases["child"] = aliases.pop("relation")
    if "relation_key" in aliases and "child_key" not in aliases:
        aliases["child_key"] = aliases.pop("relation_key")
    return Relationship(**aliases)
